[package]
name = "zsign"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = "0.10"
openssl-sys = "0.9"
goblin = "0.8"
zip = "2.1"
plist = "1.7"
sha1 = "0.10"
sha2 = "0.10"
thiserror = "1.0"
memmap2 = "0.9"
walkdir = "2.5"
tempfile = "3.10"
base64 = "0.22"
